### ISSUE TITLE
Oauth failed, all of a sudden

### ISSUE THREAD

**Issue by roccolord** [jaroschek/home-assistant-myuplink#171]
My credentials just broke without doing any change:

Token request for myuplink_xxxxxxx failed (invalid_grant): check authorization server configuration

I have not changed the credentials, have myuplink changed something?

![image](https://github.com/user-attachments/assets/d893f51d-8332-44ea-aeaa-4d4d6775dbee)

**Comment by roccolord** [comment]
I had to remove and add the integration again with new credentials. New entities, lost stats. bummer.

**Comment by Discolai** [comment]
I had the same issue, but I managed to fix it without removing the integration and loosing old data.
1. Disable my current integration entry.
2. Add the integration back again.
3. Complete the setup of a new integration entry.
4. Disable the new integration entry.
5. Enable the old entry again.
6. Delete the new entry

This seems to have tricked home assistant to use the credentials generated by the new integration entry.

**Comment by ChrispyGee** [comment]
@Discolai Great tip.  I had the same sort of problem this week, followed your tip and it's working once more. Thank you

**Comment by BogdanVosnjak** [comment]
I tried the workaround from Discolai, but got stuck at step 5. The old entry would not enable. So, I used the new entry and lost all historical data. It was working for 1 hour, then it broke down again. The error is slightly different now:

![image](https://github.com/user-attachments/assets/0cc629a8-aa43-4364-8594-2edb81709361)

But the errors in the logs still revolve around oauth2 and the token:

This error originated from a custom integration.

Logger: custom_components.myuplink
Source: helpers/update_coordinator.py:382
integration: myUplink-jaroschek (documentation, issues)
First occurred: 18:00:30 (27 occurrences)
Last logged: 20:10:30

Unexpected error fetching myUplink data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/__init__.py", line 62, in async_update_data
    return await api.get_systems()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/api.py", line 603, in get_systems
    resp = await self.auth.request("get", "systems/me?page=1&itemsPerPage=99")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/api.py", line 69, in request
    access_token = await self.async_get_access_token()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/api.py", line 56, in async_get_access_token
    await self._oauth_session.async_ensure_token_valid()
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 531, in async_ensure_token_valid
    new_token = await self.implementation.async_refresh_token(self.token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 103, in async_refresh_token
    new_token = await self._async_refresh_token(token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 197, in _async_refresh_token
    "refresh_token": token["refresh_token"],
                     ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'

**Comment by siggeb** [comment]
I followed the instructions above and was able to retain the old entities and values. The only thing, is that I think there are fewer entities available now. I had over 100 and now there are only 54. Something happened with the API for sure, and they saw this when logging into dev.myuplink....
I have als now set up modbus that finally works, so the question is if I want to keep myuplink in the future...

**Comment by Siggy101** [comment]
> I followed the instructions above and was able to retain the old entities and values. The only thing, is that I think there are fewer entities available now. I had over 100 and now there are only 54. Something happened with the API for sure, and they saw this when logging into dev.myuplink.... I have als now set up modbus that finally works, so the question is if I want to keep myuplink in the future...

There was for sure a change in the API. I went from ~150 to over 300 entities. 

@siggeb  That's very interesting that you got modbus working.
May I ask if you can share any documentation that you followed? I'd love to do the same.

**Comment by siggeb** [comment]
I was heavily inspired by this: https://github.com/gribber/ha/blob/main/modbus/ctc.yaml
I was having huge issues getting it running, but was had a half-baked setup also in homey, which was tampeing with the ha setup...

**Comment by Siggy101** [comment]
Grazie mille!
