### ISSUE TITLE
Integration stop working

### ISSUE THREAD

**Issue by simonepittis** [jaroschek/home-assistant-myuplink#84]
Version 1.2.0

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 14:55:44 (1 occurrences)
Last logged: 14:55:44

Error setting up entry Boiler for myuplink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/__init__.py", line 73, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/__init__.py", line 55, in async_update_data
    return await api.get_systems()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/api.py", line 508, in get_systems
    await system.async_fetch_data()
  File "/config/custom_components/myuplink/api.py", line 459, in async_fetch_data
    await device.async_fetch_data()
  File "/config/custom_components/myuplink/api.py", line 408, in async_fetch_data
    self.parameters = await self.system.api.get_parameters(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myuplink/api.py", line 544, in get_parameters
    async with self.lock, self.throttle:
  File "/config/custom_components/myuplink/api.py", line 476, in __aenter__
    await asyncio.sleep(delay)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by simonepittis** [comment]
rollback to version 1.1.6 and works... but good work :-)

**Comment by jaroschek** [comment]
Thanks! I made some research regarding this error. And it seemed to be caused from some other process cancelling the sleep task that ist used to throttle the api calls.

The common solution seems to be to just suppress this error. I have prepare a pre-release that you could test:
https://github.com/jaroschek/home-assistant-myuplink/releases/tag/1.2.1-rc1

**Comment by simonepittis** [comment]
the change works. no errors and the device loads without problems. Thanks
